http://localhost:3000/users?firstName=Jane

###
http://localhost:3000/users?firstName=Nikolas

###
http://localhost:3000/users?firstName=Mary

###
http://localhost:3000/users?firstName=Cole

### 
http://localhost:3000/users?firstName=Johann

###
http://localhost:3000/users?firstName=Pamela

###
http://localhost:3000/users?firstName=Franklin

###
http://localhost:3000/users?firstName=Anne

###
http://localhost:3000/users?firstName=Jimmy